version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "StrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - mssql-network

  sqlcmd:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    entrypoint: >
      /bin/bash -c "
      sleep 20 &&
      /opt/mssql-tools/bin/sqlcmd -S db -U sa -P StrongPassword123 -Q \"
      IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'farm')
      BEGIN
        CREATE DATABASE farm;
      END\"
      "
    networks:
      - mssql-network

networks:
  mssql-network:
